version: "3.9"
services:

  mongo:
    image: mongo:5.0.14
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017 # for dev, remove this later


  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - "mongo"


  nodejs: # TODO: make this depend on mongo
    build: ./pdf-editor-backend
    volumes:
      - ./pdf-editor-backend/storage:/usr/src/app/storage
      - ./pdf-editor-backend/logging/logs:/usr/src/app/logging/logs
    depends_on:
      - "mongo"


  nginx-backend:
    restart: always
    build: ./pdf-editor-backend/nginx/
    ports:
      - "5000:80"
    depends_on:
      - "nodejs"


  react-frontend:
    build: ./pdf-editor-frontend
    ports:
      - "8082:80"