version: "3.9"
services:

  nodejs:
    build: ./pdf-editor-backend
    ports:
      - "3000:3000"
  
  react-frontend:
    build: ./pdf-editor-frontend
    ports:
      - "8082:80"

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"