FROM node:16-apline

# optimize for production
ENV NODE_ENV production

WORKDIR /usr/src/app

COPY --chown=node:node . /usr/src/app/

RUN npm ci --only=production

USER node

EXPOSE 3000

CMD [ "node", "app.js" ]