name: Deploy NodeJS Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          docker compose build
          docker compose stop
          docker compose rm
          docker compose up -d
        working-directory: .