name: Deploy Project To Digital OCean

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          docker compose build
          docker compose rm -fs
          docker compose up -d --remove-orphans
        working-directory: .